### ISSUE TITLE
The navigation bar is not displayed properly. [Screenshots attached for reference]

### ISSUE THREAD

**Issue by thesketchydev** [casbin/casbin-website-v2#141]
**Links in the navigation bar are not properly rendered.** 

<img width="1244" alt="Screenshot 2023-01-21 at 11 30 57 PM" src="https://user-images.githubusercontent.com/122589409/213881056-dc0dbc25-3a40-4d1e-9ee2-d3d97d2ac2fa.png">

**Links present in the navigation bar overlap with various sections of the webpage upon scrolling.**

<img width="1244" alt="Screenshot 2023-01-21 at 11 31 31 PM" src="https://user-images.githubusercontent.com/122589409/213881062-fc5710cf-0038-464f-9bb1-806b4e0c211c.png">

**Comment by thesketchydev** [comment]
Hi @hsluoyz ,
I'm new to open source contribution. This could be my potential first issue. Please assign me so that I could work on it :)

**Comment by ZhengLin-Li** [comment]
Is this what you mean when we set the size to 150% and 175%?

![image](https://user-images.githubusercontent.com/63448884/213908982-1b6c3a51-1499-4626-8b32-e3a7d720f50d.png)

**Comment by thesketchydev** [comment]
@ZhengLin-Li  it happens at 100% as well.
<img width="1244" alt="Screenshot 2023-01-22 at 3 48 48 PM" src="https://user-images.githubusercontent.com/122589409/213911022-03c2a757-1839-443e-bcd7-a4bc9232795b.png">

**Comment by thesketchydev** [comment]
@ZhengLin-Li I went ahead to solve it and submitted a PR. (changing the default size of the NavBar fixes it)

**Comment by thesketchydev** [comment]
@ZhengLin-Li  I think this issue was not detected by your system as it runs light mode and therefore the anomaly is not easily detected as the foreground and background is identical. Try out the dark mode and it will easily be noticeable.

**Comment by hsluoyz** [comment]
If anyone targets for participating in any programs instead of purely using Casbin, he/she should fix existing issues in the list, not propose a new one. We tend to let real users propose real problems in their real-world development instead of new contributors find an easy task and resolve it by themselves.

BTW I don't know why so many people want to propose this issue again and again:

![image](https://user-images.githubusercontent.com/3787410/213917368-f4474440-47e4-4a8c-aa21-b4f1a989e8fb.png)

In my view, this is just because there are so many texts to show within a limited screen width, which is not a really big issue. To avoid over-heated situation among new contributors attracted by various programs, we decide to freeze this issue within this year.
