### ISSUE TITLE
Casbin.org AI chat, IP based historic?

### ISSUE THREAD

**Issue by TheLifeIsYours** [casbin/casbin-website-v2#269]
### Problem
When a coworker of mine opened casbin.org and checked out the AI chat, he could see the historic of what I have written days earlier.

This is not okay.

We found out that it is browser type based, and I imagine IP based?

I am using Chrome, and my coworker then opened casbin.org for the first time also in Chrome, where they could read everything.
We also tried another browser, and opened the AI chat in Safari on their computer, it will result in a clean chat.

This is most concerning, and the AI chat should be removed until this is corrected.
The Casbin project is based on security, this does not build confidence in Casbin if this is the first thing you are met with.

### Expected
It should not share chat historic across different computers on the same network.

**Comment by hsluoyz** [comment]
Hi, the chat integtation is a 3rd-party as a demo site. All the data in the demo site based on their definition are open and shared. The data can be seen by others anyway. It's for demo purpose just like its name. So you should not share your private info there. Always choose a mature commercial solution like ChatGPT Pro for that case. As a side note, that's also an OSS project, contribute to it for better feature if you want. For further issues, you should also resort to their project instead of here.

**Comment by TheLifeIsYours** [comment]
I luckily haven't shared any private information in these chats. But it is concerning that there is no warning at all that other people can see what you have written into the AI Chat. I do not feel like this integration belongs on a website about security, when the chat application in itself is not secure. My issue lays more in that Casbin.org uses it at all at this point, than the inherited security risks of it.
